import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import TransitionEffect from "@/components/TransitionEffect";
import { motion } from "framer-motion";
//
import fng from "../../public/images/fng.svg";
import ReactTypingEffect from "react-typing-effect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Face Nord Graphisme | Webdesigner</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <motion.main
        initial={{ opacity: 0, y: "-80%" }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, x: "-80%" }}
        transition={{
          ease: "linear",
          duration: 1,
          x: { duration: 1 },
        }}
        className="flex items-center text-dark w-full min-h-screen dark:text-light"
      >
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <Image
                src={profilePic}
                alt="FaceNordGraphisme"
                className="w-full h-auto lg:hidden md:inline-block md:w-full opacity-40"
                priority
                sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <motion.div
                initial={{ opacity: 0, x: "-40%" }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: 0 }}
                transition={{
                  ease: "linear",
                  duration: 2,
                  x: { duration: 2 },
                }}
              >
                <Image
                  src={fng}
                  alt="casseCouilles"
                  className="w-[600px] h-auto md:w-[400px] pb-5"
                  priority
                  sizes="(max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  50vw"
                />
              </motion.div>
              {/* <AnimatedText
                text="Face nord graphisme"
                className="!text-8xl !text-center xl:!text-6xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl text-dark my-5 "
              /> */}
              <h2 className="!text-6xl !text-left xl:!text-5xl lg:!text-left lg:!text-5xl md:!text-5xl sm:!text-3xl text-prim2 my-5">
                <ReactTypingEffect
                  text={[
                    "Création de site web",
                    "Infographies",
                    "Identité visuelle",
                    "Référencement",
                  ]}
                  speed={60}
                  eraseDelay={1000}
                  typingDelay={500}
                />
              </h2>
              <AnimatedText
                text="Prenez de la hauteur en créant un site à votre image."
                className="!text-3xl !text-center xl:!text-3xl lg:!text-center lg:!text-2xl md:!text-2xl sm:!text-xl text-prim2 my-5 "
              />
              <p className="my-4 text-center text-lg font-medium md:text-sm sm:text-xs">
                Je réside dans les Hautes Alpes aux abords du lac de Serre
                Ponçon. Webdesigner depuis plusieurs années, je vous propose mes
                services.
              </p>
              <div className="flex items-center justify-center mt-2 lg:self-center gap-8">
                <Link
                  href="/about"
                  className="flex items-center bg-prim2 text-light p-5 px-10 rounded-lg text-lg font-md hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                >
                  Découvir
                </Link>
                <Link
                  href="mailto:abcd@gmail.com"
                  target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        {/* <div className="absolute right-8 bottom-8 inline-block w-48 lg:w-48 md:hidden">
          <Image
            src="https://upload.wikimedia.org/wikipedia/commons/1/12/Mountains-By-The-Icon-Z-3322972.svg"
            alt="FaceNordGraphisme"
            className="w-full h-auto"
          />
        </div> */}
      </motion.main>
    </>
  );
}
