import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import HireMe from "@/components/HireMe";
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg";
import { motion } from "framer-motion";
//
import styles from "../styles/Home.module.css";
import fng from "../../public/images/fng.svg";
import ReactTypingEffect from "react-typing-effect";
import Experience from "@/components/Experience";
import Tarifs from "@/components/Tarifs";
import Education from "@/components/Education";
import lines from "../../public/images/lines.png";
import bg from "../../public/images/bg/bg1.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Face Nord Graphisme | Webdesigner</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {/* //Background */}
      <div className="fixed bg top-0 w-full h-full opacity-60">
        <Image
          src={bg}
          alt="casseCouilles"
          className="w-full h-full object-cover"
          priority
        />
      </div>
      {/* Hero */}
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light rounded-2xl">
        <Layout className="pt-0 md:pt-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full">
              <motion.div
                initial={{ opacity: 0, scale: 2 }}
                animate={{ opacity: 1, scale: 1 }}
                exit={{ opacity: 0, scale: 0 }}
                transition={{
                  ease: "linear",
                  duration: 0.5,
                }}
                whileHover={{ scale: 1.05 }}
              >
                <Image
                  src={profilePic}
                  alt="FaceNordGraphisme"
                  className="w-full h-auto lg:hidden md:inline-block md:w-full mb-4 rounded-full opacity-50"
                  priority
                  sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              50vw"
                />
                <h3 className="px-16 !text-xl !text-center lg:!text-center md:!text-lg sm:!text-lg text-prim2 my-2 italic">
                {'"'}Le bonheur n{"'"}est pas au sommet de la montagne mais dans la
                façon de la gravir.{'"'} -Confucius
              </h3>
              </motion.div>
            </div>
            <motion.div
              initial={{ opacity: 0, scale: 0.1 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 1.5 }}
              transition={{
                ease: "linear",
                duration: 0.5,
              }}
              className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center"
            >
              <div>
                <Image
                  src={fng}
                  alt="casseCouilles"
                  className="w-[500px] h-auto md:w-[250px] "
                  priority
                  sizes="(max-width: 768px) 100vw,
                  (max-width: 1200px) 50vw,
                  50vw"
                />
              </div>
              <h2 className="text-2xl font-bold mb-4">Propulsez votre entreprise au sommet.</h2>
              {/* <AnimatedText
                text="Face nord graphisme"
                className="!text-8xl !text-center xl:!text-6xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl text-dark my-5 "
              /> */}
              <h2 className="!text-4xl !text-left xl:!text-3xl lg:!text-left lg:!text-3xl md:!text-3xl sm:!text-3xl text-prim2 my-2">
                <ReactTypingEffect
                  text={[
                    "Création de site web",
                    "Infographies",
                    "Identité visuelle",
                    "Référencement",
                  ]}
                  speed={60}
                  eraseDelay={1000}
                  typingDelay={500}
                />
              </h2>
              <p className="my-4 text-center text-2xl font-semibold md:text-sm sm:text-xs px-8">
                Offrez à votre entreprise la visibilité qu{"'"}elle mérite et attirez de nouveaux clients.
              </p>
              <div className="flex items-center justify-center mt-2 lg:self-center gap-8">
                <Link
                  smooth
                  href="#exp"
                  className="group relative bg-transparent border-1 border-black rounded-lg overflow-hidden px-10 py-2.5 text-dark text-xl font-semibold hover:text-transparent"
                  page="exp"
                >
                  Me décrouvrir
                  <span className="absolute w-64 h-64 mt-12 group-hover:-rotate-45 group-hover:-mt-24 transition-all ease-out duration-1000 bg-prim2 left-0 top-0"></span>
                  <span className="absolute right-12 top-2.5 text-transparent group-hover:text-light font-medium text-md">
                    Compétences{" "}
                    <span className="absolute -right-5 bottom-0">&#10095;</span>
                  </span>
                </Link>
                <Link
                  href="/contact"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact
                </Link>
              </div>
            </motion.div>
          </div>
        </Layout>
        <HireMe />
        {/* <div className="absolute right-8 bottom-8 inline-block w-48 lg:w-48 md:hidden">
          <Image
          src="https://upload.wikimedia.org/wikipedia/commons/1/12/Mountains-By-The-Icon-Z-3322972.svg"
          alt="FaceNordGraphisme"
          className="w-full h-auto"
          />
        </div> */}
      </main>
      <div className="overflow-hidden">
        <div className="w-[120%] h-auto">
          <Image
            src={lines}
            alt="casseCouilles"
            className="w-full h-full z-50"
            priority
          />
        </div>
        <Experience />
        <div className=" flex justify-center items-center">
        <Link
                  smooth
                  href="#exp"
                  className="group relative bg-transparent border-1 border-black rounded-lg overflow-hidden px-10 py-2.5 text-dark text-xl font-semibold hover:text-transparent"
                  page="exp"
                >
                  Mes derniers projets
                  <span className="absolute w-80 h-80 mt-12 group-hover:-rotate-45 group-hover:-mt-24 transition-all ease-out duration-1000 bg-prim2 left-0 top-0"></span>
                  <span className="absolute right-12 top-2.5 text-transparent group-hover:text-light font-medium text-md">
                    Voir mon travail{" "}
                    <span className="absolute -right-5 bottom-0">&#10095;</span>
                  </span>
                </Link>
        </div>
        <Tarifs />
        <Education />
      </div>
    </>
  );
}
